### ISSUE TITLE
Introduce drone damage modifier for abyssal BCS

### ISSUE THREAD

**Issue by DarkFenX** [StephenSwat/eve-abyssal-market#2]
EVE allows to mutate both regular BCS (such as Caldari Navy Ballistic Control System) and guristas BCS (C3-X 'Hivaa Saitsuo' Ballistic Control System).

Presently it's impossible to separate them from each other w/o opening each item individually. However, if drone damage attribute was exposed for BCS to list/filters, it would fix the issue.

**Comment by StephenSwat** [comment]
Thanks for the suggestion, implemented.
