### ISSUE TITLE
Appraisal API

### ISSUE THREAD

**Issue by ficti0n1** [StephenSwat/eve-abyssal-market#23]
There are a lot of tools out there that could make great use of an appraisal API (zkillboard, jeveassets).

Could borrow some code from eveappraisal's API:
https://evepraisal.com/api-docs

I realise this isn't a quick job, rather just a brain worm 👍

**Comment by StephenSwat** [comment]
Fixed as of 9ea5f72f. The API is available at https://mutaplasmid.space/api/swagger/.
