### ISSUE TITLE
Submitting in appraisal page returns 500 or 502 error

### ISSUE THREAD

**Issue by hallmic1** [stephenswat/eve-abyssal-market#30]
entering a copied link into the page at https://mutaplasmid.space/appraisal/ gives a 500 or 502 error. 
![image](https://user-images.githubusercontent.com/10436966/107189955-6632eb00-69a7-11eb-98d7-8bf373668a86.png)

**Comment by PeacefulWhale** [comment]
Part of #36 and mentioned in #33
