### ISSUE TITLE
Improve estimated value accuracy

### ISSUE THREAD

**Issue by DarkFenX** [StephenSwat/eve-abyssal-market#5]
According to my experience, estimated value calculated by ms.space is too high. One of such reasons could be source data.

ESI provides no way to see if contract was accepted or removed. People creating contracts are often too optimistic about value of a module, so set excessively high prices in the beginning, setting lower and lower prices until contract is accepted (or until they give up).

While we have no way to see if contract was accepted or not, we can make guess that latest contract created by specific character for the module is his final decision on price so far (which might change as long as he owns the module). So, contracts for the same module created by the same character can be aggregated into set, and only price of latest contract could be taken. If another character creates contract - it should have its own set of contracts, as another character can have another judgement on price and for estimation - the more opinions on module, the better.

**Comment by StephenSwat** [comment]
Those free criteria (no auctions, no multi-item contracts and no outstanding contracts) are already in place: https://github.com/StephenSwat/eve-abyssal-market/blob/4aae928c37b877be2dcfea37d83c892a2f713d71/price_predictor/tasks.py#L24 :smile:

**Comment by StephenSwat** [comment]
I've actually taken a different approach to this issue. I found (I think) a way to determine if a contract sold or not (17fee43d403fe444647b6957eeecf51a56c9ecc8).

This is being retroactively checked for all contracts which is going to take a few days. After this is done, I'll be able to implement more accurate price models.
