### ISSUE TITLE
Make Abyssal Vorton Tuning System appear and work on site

### ISSUE THREAD

**Issue by dangarfield** [stephenswat/eve-abyssal-market#55]
As title, examples:
- https://mutaplasmid.space/module/1043476028065/
- https://mutaplasmid.space/module/1043474362249/

**Comment by PeacefulWhale** [comment]
Addressed by #56

**Comment by stephenswat** [comment]
Thanks @PeacefulWhale for addressing this.

**Comment by stephenswat** [comment]
Thanks @PeacefulWhale for addressing this.
